### ISSUE TITLE
Backend forms

### ISSUE THREAD

**Issue by nelero** [Pixel-Open/magento-cloudflare-turnstile#3]
Hi,
it could be helpful to activate turnstile on backend admin forms like login and forgot password.

**Comment by magentix** [comment]
Hi @nelero,

We are currently working on protecting admin forms :+1: 

This will be available in the 100.2.0 release, currently in testing:

https://github.com/Pixel-Open/magento-cloudflare-turnstile/tree/release/100.2.0

**Comment by magentix** [comment]
The 100.2.0 is now available!
